services:
  - type: web
    name: algolab-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEBHOOK_SECRET
        generateValue: true
